# Generated by Django 3.0.3 on 2020-03-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_id', models.IntegerField(default=-1)),
                ('capacity', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_id', models.IntegerField(default=-1)),
                ('name', models.CharField(max_length=200)),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
    ]
